### ISSUE TITLE
siren-solr: error on accessing admin, posting data or searching data

### ISSUE THREAD

**Issue by ginettev** [rdelbru/SIREn#13]
Hi,

The following error on accessing admin, posting data or searching data is being thrown:
      HTTP Status 404 - missing core name in path

I removed multi core setup from solr.xml too.
Catalina.out log is not showing up any errors.

Any help would be appreciated.
## 

Ginette

**Comment by rdelbru** [comment]
Hi Ginette,

could you give more background information about this problem ?
Is this coming from the siren-solr/example ? Have you followed the install procedure for tomcat6 ?

As a side note, the siren-solr/example is for the moment broken, I need to update the solrconfig.xml and schema.xml files to reflect the recent changes in the code. See issue #2.

**Comment by ginettev** [comment]
I have replied to issue #2 too also about class loading error

## 

Ginette

**Comment by rdelbru** [comment]
Hi Ginette,

I have made a first review of the siren-solr/example. However, I don't have the time right now to test it myself. If you would like to test it by yourself, please follow the instructions in the INSTALL.txt.
Sorry for not having tested it myself first. let me know how it goes. You should not have the need to modify the siren.xml (remove the solr core configuration).

thanks.
