### ISSUE TITLE
running query.sh in siren-solr/example not returning results

### ISSUE THREAD

**Issue by ginettev** [rdelbru/SIREn#14]
Hi,

On running query.sh in siren-solr/example I am not getting any results.
I have posted the data from people.xml and that got posted without any issues.
I loaded other data too but querying that using the siren request handler did not work either.
## 

Ginette

**Comment by ginettev** [comment]
Have fixed this.. will checkin

**Comment by blancaHernan** [comment]
How did you solve it?
Some configuration issue? Could you please add more info? I am having some problems to get results in solr-siren.
Thanks
