### ISSUE TITLE
siren-solr query - HTTP Status 500 - Can't find bundle for base name

### ISSUE THREAD

**Issue by dmerlitti** [rdelbru/SIREn#16]
Hi,
I have tried both on Windows XP and Linux Ubuntu 10.10 and I obtain the same error if I make a query with qt=siren as explained in step 9 of file siren-solr/example/INSTALL.TXT. The error stack of tomcat is the following:

HTTP Status 500 - Can't find bundle for base name org.apache.lucene.queryParser.core.messages.QueryParserMessages, locale it_IT java.util.MissingResourceException: Can't find bundle for base name org.apache.lucene.queryParser.core.messages.QueryParserMessages, locale it_IT at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539) at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1278) at java.util.ResourceBundle.getBundle(ResourceBundle.java:805) at org.apache.lucene.messages.NLS.getResourceBundleObject(NLS.java:109) at org.apache.lucene.messages.NLS.getLocalizedMessage(NLS.java:60) at org.apache.lucene.messages.NLS.getLocalizedMessage(NLS.java:70) at org.apache.lucene.messages.MessageImpl.getLocalizedMessage(MessageImpl.java:57) at org.apache.lucene.queryParser.core.QueryNodeException.getLocalizedMessage(QueryNodeException.java:82) at org.apache.lucene.queryParser.core.QueryNodeException.getLocalizedMessage(QueryNodeException.java:78) at org.apache.lucene.queryParser.core.QueryNodeException.getMessage(QueryNodeException.java:73) at org.sindice.siren.qparser.keyword.KeywordQParserImpl.parse(KeywordQParserImpl.java:69) at org.sindice.siren.solr.qparser.keyword.KeywordQParser.parse(KeywordQParser.java:125) at org.sindice.siren.solr.SirenQParser.addKeywordQuery(SirenQParser.java:105) at org.sindice.siren.solr.SirenQParser.parse(SirenQParser.java:70) at org.apache.solr.search.QParser.getQuery(QParser.java:142) at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:84) at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:173) at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129) at org.apache.solr.core.SolrCore.execute(SolrCore.java:1360) at
[CUT]

Any ideas on how to solve the problem?

Thanks

P.S.:
the file people.xml has to be changed in order to use the field name "ntriple" instead of "content". Alternatively you can change the fieldname "ntriple" in "content" in schema.xml of solr.

**Comment by rdelbru** [comment]
Hi,

this error appears normally when the query is invalid. What is the query 
you are trying to execute ?

I know that the error message is not very pretty, nor informative. I 

## will fix this issue very soon.

Renaud Delbru

**Comment by dmerlitti** [comment]
After several trials I solved the problem by moving lucene-queryparser-3.1.0.jar from solr/lib to webapps/solr/WEB-INF/lib.
