### ISSUE TITLE
Solr problems when using SIREn with multi-cores

### ISSUE THREAD

**Issue by jsteggink** [rdelbru/SIREn#17]
Hi,

I used to run SIREn with a multi-core setup. However, I've just downloaded the latest version of SIREn and it doesn't work anymore. Running the included Solr demo without using multi-cores works just fine. As soon as I change the instanceDir to something else than "." I get the following error:

SEVERE: org.apache.solr.common.SolrException: Cannot load analyzer: org.sindice.siren.solr.analysis.MultiQueryAnalyzerWrapper

I have the following core config:

(Edit: somehow XML doesn't show up in this window, so I added some spaces)

< solr persistent="false" sharedLib="lib" >
  < cores adminPath="/admin/cores" defaultCoreName="core" >
    < core name="core" instanceDir="core" / >
  < / cores >
< / solr >

I have tried moving the lib directory to different places, but no luck. Any ideas?

Regards,

J.

**Comment by rdelbru** [comment]
Hi,

I had similar problems. For multi-cores, I am not using a shared lib directory, but a shared solr home (which has its own lib directory), and each core has its own index. This is fine for configuring multiple shards on the same host. I have the following configuration:

```
<solr persistent="false">

  <cores adminPath="/admin/cores">
    <core name="core0" instanceDir=".">
      <property name="solr.data.dir" value="./data/core0" />
    </core>

    <core name="core1" instanceDir=".">
      <property name="solr.data.dir" value="./data/core1" />
    </core>

    <core name="core2" instanceDir=".">
      <property name="solr.data.dir" value="./data/core2" />
    </core>

    <core name="core3" instanceDir=".">
      <property name="solr.data.dir" value="./data/core3" />
    </core>

  </cores>
</solr>
```
