### ISSUE TITLE
SIREn in Solr indexing and making queries

### ISSUE THREAD

**Issue by marotosg** [rdelbru/SIREn#18]
Hi.

I'm trying to evaluate if i can use SIREn for some specific searches in my Solr enviroment.
I'm using Solr.Net as my api to send documents to Solr so my concern is if i can send documents
in  a xml document <doc></doc> into Solr and make queries in a http://localhost:8080/solr/query 
and get the benefits of using SIREn.
I couldn't find any documentation about that.

Thanks
Sergio

**Comment by rdelbru** [comment]
Hi Sergio,

Indeed, there is still no proper documentation about siren-solr. You can have a look at the siren-solr example [1] or the siren-solr unit tests [2] for some examples on how to use siren within solr.
It seems that there are problems to run the siren-solr example, and I haven't add the time yet to fix the problem. But it is still a good source of information to understand how siren is integrated within solr.

[1] https://github.com/rdelbru/SIREn/tree/6d0ef4c35ec029a2d2bca59b447325f6e68ad0b5/siren-solr/example
[2] https://github.com/rdelbru/SIREn/blob/6d0ef4c35ec029a2d2bca59b447325f6e68ad0b5/siren-solr/src/test/java/org/sindice/siren/solr/TestSirenQParserPlugin.java

**Comment by rdelbru** [comment]
Fixed examples, and added documentation (see wiki)
