### ISSUE TITLE
siren-solr - Solr example: class not found NTripleQParserPlugin 

### ISSUE THREAD

**Issue by paulomagalhaes** [rdelbru/SIREn#2]
I'm getting a class not found exception starting the solr example.
The cause seems to be that the conf file siren-solr\example\solr\conf\solrconfig.xml defines this query parser:

<queryParser name="ntriple" class="org.sindice.siren.solr.qparser.ntriple.NTripleQParserPlugin"/>

but  the NTripleQParserPlugin is not in anywhere in the source code.

**Comment by rdelbru** [comment]
Hi,

yes, the Solr demo has been broken by the recent changes in the solr plugin. I'll fix the demo soon. In the meanwhile, you can look at the siren-solr plugin test, and mroe particularly at the solr configuration that I use for the test.
https://github.com/rdelbru/SIREn/tree/master/siren-solr/src/test/resources/solr.home/conf

**Comment by ginettev** [comment]
Hi,

Has there been any resolution for this issue.
I would like to use this demo but it is throwing up "class not found NTripleQParserPlugin" even upon using the solrconfig from the test directory.

**Comment by rdelbru** [comment]
We fixed issues in the provided solr/example, and test the install procedure. It should now work.
