### ISSUE TITLE
Enhancement: Render results in RDF

### ISSUE THREAD

**Issue by emailrhoads** [rdelbru/SIREn#35]
Currently I'm part of a project that is trying to use SIREN and integrate the results with a linked data API.

We are now at phase in this process where we have results being fetched from the linked data API as well as some prioritization of those results as determined by SIREn.

The problem is we'd like to present the results of the SIREn query in RDF form (i.e. as a semi-persistent graph) to the linked data API so that they can be more easily incorporated into a SPARQL query. These results obviously need to be dynamically generated and from initial thoughts, this "graph of results" would ideally be owned by SIREn rather than some other intermediary code.

Ideally, these items come back in some framework such as <URI> <hasRelevancy> <###> and we'd be able to reference the graph that holds the RDF results for a given SIREN query by using the FROM NAMED syntax.
e.g. 

SELECT ?item
FROM NAMED http://localhost/siren/rdfselect/[parms]
WHERE { ?item siren:hasRelevancy ?score }
ORDER BY ASC(?score )

This would make it easier to incorporate the SIREn results into semantic web applications as well as expand the functionality of SIREn to adhere to more semantic web principles.

**Comment by rdelbru** [comment]
Hi,

That's a good idea, however, I am not sure when we will be able to implement such a feature. The right way to tackle the problem would be to create a RDFXMLResponseWriter for Solr.
You could try also to use the XsltResponseWriter with a XSLT to transform the XML output into RDF ?

[1] http://wiki.apache.org/solr/XsltResponseWriter

**Comment by rdelbru** [comment]
Deprecated
