### ISSUE TITLE
Fix demo shell script

### ISSUE THREAD

**Issue by rdelbru** [rdelbru/SIREn#37]
the name of the jar in the demo.sh script is siren-_-0.2.3-SNAPSHOT.jar, but should be siren-_-0.2.3-RC2.jar.

**Comment by scampi** [comment]
for that release candidate it is siren-_-0.2.3-RC2.jar, but when it will be a final release, I imagine it will have to be siren-_-0.2.3.jar.
What is the best way to handle that ? maybe we can have a script run at each release that replace that jar name with the correct one, in the selected files ?

**Comment by rdelbru** [comment]
I think the solution is to just put the final release name, i.e, 0.2.3.

## cheers

Renaud Delbru

**Comment by rdelbru** [comment]
Deprecated
