### ISSUE TITLE
Create a benchmark module 

### ISSUE THREAD

**Issue by rdelbru** [rdelbru/SIREn#43]

**Comment by rdelbru** [comment]
Rewritten siren query converter. Made some cleaning. See commit 597112fac1ed85bcbf1ce2639e59f11aff98d926.

**Comment by rdelbru** [comment]
Added query suite executor and default query suite. Added Readme. Fixed some bugs and did some code cleaning. See commit 3bcd63a15b496bddaac23952ccca2efac075b76b.

**Comment by scampi** [comment]
<table width="100%">
  <tr>
    <th rowspan="2"></th><th rowspan="2">Query Spec</th><th rowspan="2">OS Cache</th><th colspan="2">Query Rate (q/s)</th><th rowspan="2">Hits</th>
  </tr>  <tr>
    <th>Mean</th><th>SD</th>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="8">Mock</td><td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/high-conjunction.txt" target="_blank">high-conjunction</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">63.24</td><td style="text-align: right;">15.53</td><td style="text-align: right;">137992</td>
  </tr>
  <tr>
<td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/high-disjunction.txt" target="_blank">high-disjunction</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">12.04</td><td style="text-align: right;">3.23</td><td style="text-align: right;">6239025</td>
  </tr>
  <tr>
<td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/high-high-attribute.txt" target="_blank">high-high-attribute</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">11.53</td><td style="text-align: right;">3.13</td><td style="text-align: right;">238904</td>
  </tr>
  <tr>
<td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/high-low-attribute.txt" target="_blank">high-low-attribute</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">1671.89</td><td style="text-align: right;">303.95</td><td style="text-align: right;">7</td>
  </tr>
  <tr>
<td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/high-low-conjunction.txt" target="_blank">high-low-conjunction</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">7766.99</td><td style="text-align: right;">1006.24</td><td style="text-align: right;">0</td>
  </tr>
  <tr>
<td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/low-conjunction.txt" target="_blank">low-conjunction</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">32876.71</td><td style="text-align: right;">8705.90</td><td style="text-align: right;">0</td>
  </tr>
  <tr>
<td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/low-phrase.txt" target="_blank">low-phrase</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">14.28</td><td style="text-align: right;">3.17</td><td style="text-align: right;">337</td>
  </tr>
  <tr>
<td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/medium-phrase.txt" target="_blank">medium-phrase</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">34.25</td><td style="text-align: right;">8.79</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="8">Siren10</td><td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/high-conjunction.txt" target="_blank">high-conjunction</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">63.24</td><td style="text-align: right;">15.53</td><td style="text-align: right;">137992</td>
  </tr>
  <tr>
<td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/high-disjunction.txt" target="_blank">high-disjunction</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">12.04</td><td style="text-align: right;">3.23</td><td style="text-align: right;">6239025</td>
  </tr>
  <tr>
<td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/high-high-attribute.txt" target="_blank">high-high-attribute</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">11.53</td><td style="text-align: right;">3.13</td><td style="text-align: right;">238904</td>
  </tr>
  <tr>
<td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/high-low-attribute.txt" target="_blank">high-low-attribute</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">1671.89</td><td style="text-align: right;">303.95</td><td style="text-align: right;">7</td>
  </tr>
  <tr>
<td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/high-low-conjunction.txt" target="_blank">high-low-conjunction</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">7766.99</td><td style="text-align: right;">1006.24</td><td style="text-align: right;">0</td>
  </tr>
  <tr>
<td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/low-conjunction.txt" target="_blank">low-conjunction</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">32876.71</td><td style="text-align: right;">8705.90</td><td style="text-align: right;">0</td>
  </tr>
  <tr>
<td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/low-phrase.txt" target="_blank">low-phrase</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">14.28</td><td style="text-align: right;">3.17</td><td style="text-align: right;">337</td>
  </tr>
  <tr>
<td style="text-align: left;"><a href="https://github.com/rdelbru/SIREn/blob/wip-0.3.0/siren-benchmark/src/main/resources/query/spec/medium-phrase.txt" target="_blank">medium-phrase</a></td><td style="text-align: left;">WARM</td><td style="text-align: right;">34.25</td><td style="text-align: right;">8.79</td><td style="text-align: right;">9359</td>
  </tr>
</table>


---

<table width="100%">
  <tr>
    <th rowspan="2"></th><th rowspan="2">Index Size (MB)</th><th rowspan="2">Commit Time</th><th colspan="2">Optimise Time</th>
  </tr>  <tr>
    <th>Mean</th><th>SD</th>
  </tr>
  <tr>    <td style="text-align: left;">Mock</td><td style="text-align: right;">3964.0</td><td style="text-align: right;">6508.85</td><td style="text-align: right;">3457.07</td><td style="text-align: right;">242783.0</td>
  </tr>
  <tr>    <td style="text-align: left;">Siren10</td><td style="text-align: right;">3964.0</td><td style="text-align: right;">6508.85</td><td style="text-align: right;">3457.07</td><td style="text-align: right;">242783.0</td>
  </tr>
</table>
