### ISSUE TITLE
Create Keyword Search Query Parser

### ISSUE THREAD

**Issue by rdelbru** [rdelbru/SIREn#59]
Simple keyword search, but that takes into consideration the tree structure during matching and scoring.

Also provide an expert feature to write path queries:

```
Path = '(' Parent ':'  Child ')' Datatype?
Parent = EMPTY | Boolean
Child = Expr BINARY_OP Child | Expr
Expr = Boolean | Path
Datatype = '^^' STRING
```

Paths can be nested, mixed with boolean clauses, and combined using boolean operations.

In the case where the Chjld is a boolean clause, e.g., ( knows : renaud AND stephane ), we keep the simplest solution. This will be transformed into a twig query with two child clauses, each one with one node term query. The query processing and ranking framework will take care of ranking higher child nodes where the two terms appear together.

**Comment by scampi** [comment]
The slash is now a special lucene character. It is not listed as such, but looking at the query grammar, the character slash '/' defines in Lucene4.0 the start of a term.
This means that it must be escaped, such as ':'.

> As a side note, other characters that define the start of a term have also been added: '=' and '<' and '>'.

The consequence of not escaping '/' is the following:
Parsing the query `http://www.google.com` outputs the terms `http:`, `_` (empty token), and `www.google.com`.
I believe that the first slash separates _http:_ from the rest, and outputs next the empty token. The second slash is interpreted as an escape character, therefore comes the URL.

Extracted from [StandardSyntaxParser.jj](https://svn.apache.org/repos/asf/lucene/dev/trunk/lucene/queryparser/src/java/org/apache/lucene/queryparser/flexible/standard/parser/StandardSyntaxParser.jj)

| <#_ESCAPED_CHAR: "\" ~[] >
| <#_TERM_START_CHAR: ( ~[ " ", "\t", "\n", "\r", "\u3000", "+", "-", "!", "(", ")", ":", "^",
                           "<", ">", "=", "[", "]", "\"", "{", "}", "~", "\", "/" ]
                       | <_ESCAPED_CHAR> ) >
| <#_TERM_CHAR: ( <_TERM_START_CHAR> | <_ESCAPED_CHAR> | "-" | "+" ) >

| <TERM:      <_TERM_START_CHAR> (<_TERM_CHAR>)\*  >

**Comment by scampi** [comment]
Function NTripleQueryBuilderTest.testVisitURIPattern1()

aaa://s is not a valid URI, therefore it is not completely escaped by (@link EscapeLuceneCharacters#escape}. **Only the colon ':' is escaped**. This raises the question if characters other than ':' have also to be escaped, e.g., '=' or '/', when matching an element which is not a URI.

**Comment by scampi** [comment]
I wonder if the URI [regular expression](https://github.com/rdelbru/SIREn/blob/wip-0.2.3/siren-qparser/src/main/java/org/sindice/siren/qparser/util/EscapeLuceneCharacters.java#L44) is too restrictive.
it only recognizes text that starts with `(news|(ht|f)tp(s?))\\:` as a URI. Since we are dealing with Web Data, the data can be noisy, and typo errors can occur, e.g., `hhttp:` instead of `http:`.

**Comment by scampi** [comment]
Regarding the path query grammar:

Which part of the query should the Datatype be applied to ? Do we want to be able to specify Datatype for each node in a path ?
An easier option, and maybe less confusing would be to apply it to the leaf node, i.e., the boolean query.

**Comment by rdelbru** [comment]
Deprecated
