### ISSUE TITLE
Improvement over the benchmark result exporter

### ISSUE THREAD

**Issue by rdelbru** [rdelbru/SIREn#69]
1) API could be greatly simplified. Keep in mind that the goal is to quickly export some results from a benchmark. At the moment, we need to provide four different parameters to the CLI to get some results

./scripts/export --index Siren10 --index-dir /media/Data/Benchmark/sindice-vint-20/ --output /tmp/vint.html --q-results-dir /media/Data/Benchmark/sindice-vint-20/benchmark/

This could be simplified by one:
--index: the index directory
and using naming convention, you can:
- find automatically the results dir, the directory containing the index files, the times logs
- instead of using the posting format name (i.e. --index Siren10), use the index directory name  (i.e., sindice-vint-20)
- export the html visualisation to a subdirectory viz

2) Index size should be displayed per index files

3) There is an error in the current generation: the optimise time has a mean and SD sub-column ?

4) There should be a second option, where we can indicate two indexes, e.g., :

./scripts/export --index /media/Data/Benchmark/sindice-vint-20/ --index /media/Data/Benchmark/sindice-afor-20/

it will then create one table (in each of the subdirecotry viz of each index) that will compare the results of two benchmark, and compute some percentage to measure the difference.

**Comment by scampi** [comment]
3) the colomn "commit" and "optimise" names are swapped. The mean/SD is for the commit.
    I had a set of values for the commit, so I took those stats from it...
    It doesn't make sense to show that. I will show the total commit time.

**Comment by scampi** [comment]
1) The process and logic computation has been improved (and smplified):
    This command is all that is now needed _./scripts/export --directories /tmp/sindice-index-20/_

```
You can give more than 1 directories by separating them by ','
```

2) Done

3) Corrected

This is how it looks now

<table width="100%">
  <tr>
    <th rowspan="2"></th><th rowspan="2">Query Spec</th><th rowspan="2">OS Cache</th><th colspan="2">Query Rate (q/s)</th><th rowspan="2">Hits</th>
  </tr>  <tr>
    <th>Mean</th><th>SD</th>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="10">sindice-index-5</td><td style="text-align: left;">high-conjunction</td><td style="text-align: left;">WARM</td><td style="text-align: right;">31.03</td><td style="text-align: right;">4.93</td><td style="text-align: right;">637001</td>
  </tr>
  <tr>
<td style="text-align: left;">high-disjunction</td><td style="text-align: left;">WARM</td><td style="text-align: right;">8.07</td><td style="text-align: right;">1.92</td><td style="text-align: right;">9722924</td>
  </tr>
  <tr>
<td style="text-align: left;">high-high-attribute</td><td style="text-align: left;">WARM</td><td style="text-align: right;">34.47</td><td style="text-align: right;">9.32</td><td style="text-align: right;">654839</td>
  </tr>
  <tr>
<td style="text-align: left;">high-low-attribute</td><td style="text-align: left;">WARM</td><td style="text-align: right;">1284.11</td><td style="text-align: right;">28.54</td><td style="text-align: right;">47</td>
  </tr>
  <tr>
<td style="text-align: left;">high-low-conjunction</td><td style="text-align: left;">WARM</td><td style="text-align: right;">586.44</td><td style="text-align: right;">84.98</td><td style="text-align: right;">100</td>
  </tr>
  <tr>
<td style="text-align: left;">high-phrase</td><td style="text-align: left;">WARM</td><td style="text-align: right;">1.87</td><td style="text-align: right;">0.43</td><td style="text-align: right;">3301808</td>
  </tr>
  <tr>
<td style="text-align: left;">low-conjunction</td><td style="text-align: left;">WARM</td><td style="text-align: right;">41748.21</td><td style="text-align: right;">603.19</td><td style="text-align: right;">1</td>
  </tr>
  <tr>
<td style="text-align: left;">low-phrase</td><td style="text-align: left;">WARM</td><td style="text-align: right;">348.33</td><td style="text-align: right;">14.12</td><td style="text-align: right;">378</td>
  </tr>
  <tr>
<td style="text-align: left;">medium-conjunction</td><td style="text-align: left;">WARM</td><td style="text-align: right;">5035.67</td><td style="text-align: right;">134.81</td><td style="text-align: right;">1165</td>
  </tr>
  <tr>
<td style="text-align: left;">medium-phrase</td><td style="text-align: left;">WARM</td><td style="text-align: right;">79.99</td><td style="text-align: right;">1.66</td><td style="text-align: right;">31255</td>
  </tr>
</table>


---

<table width="100%">
  <tr>
    <th rowspan="2"></th><th colspan="4">Index Size (MB)</th><th rowspan="2">Commit Time (ms)</th><th rowspan="2">Optimise Time (ms)</th>
  </tr>  <tr>
    <th>Doc</th><th>Nod</th><th>Pos</th><th>Skp</th>
  </tr>
  <tr>    <td style="text-align: left;">sindice-index-5</td><td style="text-align: right;">125.69</td><td style="text-align: right;">664.39</td><td style="text-align: right;">149.87</td><td style="text-align: right;">0.34</td><td style="text-align: right;">21582.0</td><td style="text-align: right;">99131.0</td>
  </tr>
</table>


---

**Comment by scampi** [comment]
4) It is now possible to compare a set of directories using the `--diff` option:

```
`./scripts/export --directories /tmp/sindice-pfor-20/,/tmp/sindice-afor-20/,/tmp/sindice-vint-20/ --diff`
```

This will create the file diff.html into the "viz" sub-folder of each directory.

> In _/tmp/sindice-afor-20/viz/diff.html_

<table width="100%">
  <tr>
    <th rowspan="2"></th><th rowspan="2">OS Cache</th><th rowspan="2">Directory</th><th colspan="2">Query Rate (q/s)</th><th rowspan="2">Hits</th>
  </tr>  <tr>
    <th>Mean</th><th>SD</th>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="3">high-conjunction</td><td style="text-align: left;" rowspan="3">WARM</td><td style="text-align: left;">sindice-afor-20</td><td style="text-align: right;">103.50</td><td style="text-align: right;">0.65</td><td style="text-align: right;">137992</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-pfor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">137992</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-vint-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">137992</td>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="3">high-low-conjunction</td><td style="text-align: left;" rowspan="3">WARM</td><td style="text-align: left;">sindice-afor-20</td><td style="text-align: right;">10888.98</td><td style="text-align: right;">135.22</td><td style="text-align: right;">0</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-pfor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">0</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-vint-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">0</td>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="6">low-phrase</td><td style="text-align: left;" rowspan="3">COLD</td><td style="text-align: left;">sindice-afor-20</td><td style="text-align: right;">51.44</td><td style="text-align: right;">1.93</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-pfor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-vint-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>
<td style="text-align: left;" rowspan="3">WARM</td><td style="text-align: left;">sindice-afor-20</td><td style="text-align: right;">20.00</td><td style="text-align: right;">0.13</td><td style="text-align: right;">337</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-pfor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">337</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-vint-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">337</td>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="3">medium-phrase</td><td style="text-align: left;" rowspan="1">COLD</td><td style="text-align: left;">sindice-vint-20</td><td style="text-align: right;">51.44</td><td style="text-align: right;">1.93</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>
<td style="text-align: left;" rowspan="2">WARM</td><td style="text-align: left;">sindice-afor-20</td><td style="text-align: right;">51.44</td><td style="text-align: right;">1.93</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-pfor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">9359</td>
  </tr>
</table>


---

<table width="100%">
  <tr>
    <th rowspan="2"></th><th colspan="4">Index Size (MB)</th><th rowspan="2">Commit Time (ms)</th><th rowspan="2">Optimise Time (ms)</th>
  </tr>  <tr>
    <th>Doc</th><th>Nod</th><th>Pos</th><th>Skp</th>
  </tr>
  <tr>    <td style="text-align: left;">sindice-afor-20</td><td style="text-align: right;">0.00</td><td style="text-align: right;">0.00</td><td style="text-align: right;">0.00</td><td style="text-align: right;">0.00</td><td style="text-align: right;">1050.0</td><td style="text-align: right;">1670.0</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-pfor-20</td><td style="color:red; font-style: italic; text-align: right;">+7840.00%</td><td style="color:red; font-style: italic; text-align: right;">+7840.00%</td><td style="color:red; font-style: italic; text-align: right;">+7840.00%</td><td style="color:red; font-style: italic; text-align: right;">+7840.00%</td><td style="color:green; font-style: italic; text-align: right;">-4.76%</td><td style="color:green; font-style: italic; text-align: right;">-10.18%</td>  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-vint-20</td><td style="color:red; font-style: italic; text-align: right;">+720.00%</td><td style="color:red; font-style: italic; text-align: right;">+720.00%</td><td style="color:red; font-style: italic; text-align: right;">+720.00%</td><td style="color:red; font-style: italic; text-align: right;">+720.00%</td><td style="color:red; font-style: italic; text-align: right;">+86.00%</td><td style="color:red; font-style: italic; text-align: right;">+29.94%</td>  </tr>
</table>


---

> In _/tmp/sindice-vint-20/viz/diff.html_

<table width="100%">
  <tr>
    <th rowspan="2"></th><th rowspan="2">OS Cache</th><th rowspan="2">Directory</th><th colspan="2">Query Rate (q/s)</th><th rowspan="2">Hits</th>
  </tr>  <tr>
    <th>Mean</th><th>SD</th>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="3">high-conjunction</td><td style="text-align: left;" rowspan="3">WARM</td><td style="text-align: left;">sindice-vint-20</td><td style="text-align: right;">103.50</td><td style="text-align: right;">0.65</td><td style="text-align: right;">137992</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-afor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">137992</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-pfor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">137992</td>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="3">high-low-conjunction</td><td style="text-align: left;" rowspan="3">WARM</td><td style="text-align: left;">sindice-vint-20</td><td style="text-align: right;">10888.98</td><td style="text-align: right;">135.22</td><td style="text-align: right;">0</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-afor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">0</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-pfor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">0</td>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="6">low-phrase</td><td style="text-align: left;" rowspan="3">COLD</td><td style="text-align: left;">sindice-vint-20</td><td style="text-align: right;">51.44</td><td style="text-align: right;">1.93</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-afor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-pfor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>
<td style="text-align: left;" rowspan="3">WARM</td><td style="text-align: left;">sindice-vint-20</td><td style="text-align: right;">20.00</td><td style="text-align: right;">0.13</td><td style="text-align: right;">337</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-afor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">337</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-pfor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">337</td>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="3">medium-phrase</td><td style="text-align: left;" rowspan="1">COLD</td><td style="text-align: left;">sindice-vint-20</td><td style="text-align: right;">51.44</td><td style="text-align: right;">1.93</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>
<td style="text-align: left;" rowspan="2">WARM</td><td style="text-align: left;">sindice-afor-20</td><td style="text-align: right;">51.44</td><td style="text-align: right;">1.93</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-pfor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">9359</td>
  </tr>
</table>


---

<table width="100%">
  <tr>
    <th rowspan="2"></th><th colspan="4">Index Size (MB)</th><th rowspan="2">Commit Time (ms)</th><th rowspan="2">Optimise Time (ms)</th>
  </tr>  <tr>
    <th>Doc</th><th>Nod</th><th>Pos</th><th>Skp</th>
  </tr>
  <tr>    <td style="text-align: left;">sindice-vint-20</td><td style="text-align: right;">0.00</td><td style="text-align: right;">0.00</td><td style="text-align: right;">0.00</td><td style="text-align: right;">0.00</td><td style="text-align: right;">1953.0</td><td style="text-align: right;">2170.0</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-afor-20</td><td style="color:green; font-style: italic; text-align: right;">-87.80%</td><td style="color:green; font-style: italic; text-align: right;">-87.80%</td><td style="color:green; font-style: italic; text-align: right;">-87.80%</td><td style="color:green; font-style: italic; text-align: right;">-87.80%</td><td style="color:green; font-style: italic; text-align: right;">-46.24%</td><td style="color:green; font-style: italic; text-align: right;">-23.04%</td>  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-pfor-20</td><td style="color:red; font-style: italic; text-align: right;">+868.29%</td><td style="color:red; font-style: italic; text-align: right;">+868.29%</td><td style="color:red; font-style: italic; text-align: right;">+868.29%</td><td style="color:red; font-style: italic; text-align: right;">+868.29%</td><td style="color:green; font-style: italic; text-align: right;">-48.80%</td><td style="color:green; font-style: italic; text-align: right;">-30.88%</td>  </tr>
</table>


---

> In _/tmp/sindice-pfor-20/viz/diff.html_

<table width="100%">
  <tr>
    <th rowspan="2"></th><th rowspan="2">OS Cache</th><th rowspan="2">Directory</th><th colspan="2">Query Rate (q/s)</th><th rowspan="2">Hits</th>
  </tr>  <tr>
    <th>Mean</th><th>SD</th>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="3">high-conjunction</td><td style="text-align: left;" rowspan="3">WARM</td><td style="text-align: left;">sindice-pfor-20</td><td style="text-align: right;">103.50</td><td style="text-align: right;">0.65</td><td style="text-align: right;">137992</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-afor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">137992</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-vint-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">137992</td>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="3">high-low-conjunction</td><td style="text-align: left;" rowspan="3">WARM</td><td style="text-align: left;">sindice-pfor-20</td><td style="text-align: right;">10888.98</td><td style="text-align: right;">135.22</td><td style="text-align: right;">0</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-afor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">0</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-vint-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">0</td>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="6">low-phrase</td><td style="text-align: left;" rowspan="3">COLD</td><td style="text-align: left;">sindice-pfor-20</td><td style="text-align: right;">51.44</td><td style="text-align: right;">1.93</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-afor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-vint-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>
<td style="text-align: left;" rowspan="3">WARM</td><td style="text-align: left;">sindice-pfor-20</td><td style="text-align: right;">20.00</td><td style="text-align: right;">0.13</td><td style="text-align: right;">337</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-afor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">337</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-vint-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">337</td>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="3">medium-phrase</td><td style="text-align: left;" rowspan="1">COLD</td><td style="text-align: left;">sindice-vint-20</td><td style="text-align: right;">51.44</td><td style="text-align: right;">1.93</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>
<td style="text-align: left;" rowspan="2">WARM</td><td style="text-align: left;">sindice-pfor-20</td><td style="text-align: right;">51.44</td><td style="text-align: right;">1.93</td><td style="text-align: right;">9359</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-afor-20</td><td style="color:green; font-style: italic; text-align: right;">0.00%</td><td style="color:green; font-style: italic; text-align: right;">0.00</td><td style="text-align: right;">9359</td>
  </tr>
</table>


---

<table width="100%">
  <tr>
    <th rowspan="2"></th><th colspan="4">Index Size (MB)</th><th rowspan="2">Commit Time (ms)</th><th rowspan="2">Optimise Time (ms)</th>
  </tr>  <tr>
    <th>Doc</th><th>Nod</th><th>Pos</th><th>Skp</th>
  </tr>
  <tr>    <td style="text-align: left;">sindice-pfor-20</td><td style="text-align: right;">0.00</td><td style="text-align: right;">0.00</td><td style="text-align: right;">0.00</td><td style="text-align: right;">0.00</td><td style="text-align: right;">1000.0</td><td style="text-align: right;">1500.0</td>
  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-afor-20</td><td style="color:green; font-style: italic; text-align: right;">-98.74%</td><td style="color:green; font-style: italic; text-align: right;">-98.74%</td><td style="color:green; font-style: italic; text-align: right;">-98.74%</td><td style="color:green; font-style: italic; text-align: right;">-98.74%</td><td style="color:red; font-style: italic; text-align: right;">+5.00%</td><td style="color:red; font-style: italic; text-align: right;">+11.33%</td>  </tr>
  <tr>    <td style="font-style: italic; text-align: left;">sindice-vint-20</td><td style="color:green; font-style: italic; text-align: right;">-89.67%</td><td style="color:green; font-style: italic; text-align: right;">-89.67%</td><td style="color:green; font-style: italic; text-align: right;">-89.67%</td><td style="color:green; font-style: italic; text-align: right;">-89.67%</td><td style="color:red; font-style: italic; text-align: right;">+95.30%</td><td style="color:red; font-style: italic; text-align: right;">+44.67%</td>  </tr>
</table>


---

**Comment by scampi** [comment]
I modified the DIFF output so that it matches the tables in [LUCENE-3892](https://issues.apache.org/jira/browse/LUCENE-3892).
Now, each  row reports the _QPS mean_, and for each comparison the _Pct Diff_ with the baseline.

The Pct Diff is computed as in [benchUtil.py](http://code.google.com/a/apache-extras.org/p/luceneutil/source/browse/benchUtil.py#928) (lines 928 to 945). The 1st percentage is the difference in percentage of the worst compared QPS with the best QPS of the baseline. The 2nd percentage is the difference in percentage of the best compared QPS with the worst QPS of the baseline.

> This means that if the first value is positive, the compared algorithm is better than the baseline for sure. However, if the 2nd value is negative, it means that the compared algorithm is worst than the baseline for sure.

<table width="100%">
  <tr>
    <th rowspan="2"></th><th rowspan="2">OS Cache</th><th rowspan="2">Index</th><th colspan="2">Query Rate (q/s)</th><th rowspan="2">Hits</th>
  </tr>  <tr>
    <th>Mean</th><th>Pct Diff</th>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="3">high-conjunction</td><td style="text-align: left;" rowspan="3">WARM</td><td style="text-align: left;">sindice-afor-20</td><td style="text-align: right;">103.50</td><td></td><td style="text-align: right;">137992</td>
  </tr>
  <tr>
<td style="font-style:italic; text-align: left;">sindice-pfor-20</td><td style="font-style:italic; text-align: right;">103.50</td><td style="font-style:italic; text-align: right;">(<font color="green">0%</font>   -   0%)</td><td style="font-style:italic; text-align: right;">137992</td>
  </tr>
  <tr>
<td style="font-style:italic; text-align: left;">sindice-vint-20</td><td style="font-style:italic; text-align: right;">103.50</td><td style="font-style:italic; text-align: right;">(<font color="green">0%</font>   -   0%)</td><td style="font-style:italic; text-align: right;">137992</td>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="3">high-low-conjunction</td><td style="text-align: left;" rowspan="3">WARM</td><td style="text-align: left;">sindice-afor-20</td><td style="text-align: right;">10888.98</td><td></td><td style="text-align: right;">0</td>
  </tr>
  <tr>
<td style="font-style:italic; text-align: left;">sindice-pfor-20</td><td style="font-style:italic; text-align: right;">10888.98</td><td style="font-style:italic; text-align: right;">(<font color="green">0%</font>   -   0%)</td><td style="font-style:italic; text-align: right;">0</td>
  </tr>
  <tr>
<td style="font-style:italic; text-align: left;">sindice-vint-20</td><td style="font-style:italic; text-align: right;">10888.98</td><td style="font-style:italic; text-align: right;">(<font color="green">0%</font>   -   0%)</td><td style="font-style:italic; text-align: right;">0</td>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="6">low-phrase</td><td style="text-align: left;" rowspan="3">COLD</td><td style="text-align: left;">sindice-afor-20</td><td style="text-align: right;">51.44</td><td></td><td style="text-align: right;">9359</td>
  </tr>
  <tr>
<td style="font-style:italic; text-align: left;">sindice-pfor-20</td><td style="font-style:italic; text-align: right;">51.44</td><td style="font-style:italic; text-align: right;">(<font color="green">0%</font>   -   0%)</td><td style="font-style:italic; text-align: right;">9359</td>
  </tr>
  <tr>
<td style="font-style:italic; text-align: left;">sindice-vint-20</td><td style="font-style:italic; text-align: right;">51.44</td><td style="font-style:italic; text-align: right;">(<font color="green">0%</font>   -   0%)</td><td style="font-style:italic; text-align: right;">9359</td>
  </tr>
  <tr>
<td style="text-align: left;" rowspan="3">WARM</td><td style="text-align: left;">sindice-afor-20</td><td style="text-align: right;">20.00</td><td></td><td style="text-align: right;">337</td>
  </tr>
  <tr>
<td style="font-style:italic; text-align: left;">sindice-pfor-20</td><td style="font-style:italic; text-align: right;">20.00</td><td style="font-style:italic; text-align: right;">(<font color="green">0%</font>   -   0%)</td><td style="font-style:italic; text-align: right;">337</td>
  </tr>
  <tr>
<td style="font-style:italic; text-align: left;">sindice-vint-20</td><td style="font-style:italic; text-align: right;">20.00</td><td style="font-style:italic; text-align: right;">(<font color="green">0%</font>   -   0%)</td><td style="font-style:italic; text-align: right;">337</td>
  </tr>
  <tr>
    <td style="text-align: left;" rowspan="3">medium-phrase</td><td style="text-align: left;" rowspan="1">COLD</td><td style="text-align: left;">sindice-vint-20</td><td style="text-align: right;">51.44</td><td></td><td style="text-align: right;">9359</td>
  </tr>
  <tr>
<td style="text-align: left;" rowspan="2">WARM</td><td style="text-align: left;">sindice-afor-20</td><td style="text-align: right;">51.44</td><td></td><td style="text-align: right;">9359</td>
  </tr>
  <tr>
<td style="font-style:italic; text-align: left;">sindice-pfor-20</td><td style="font-style:italic; text-align: right;">51.44</td><td style="font-style:italic; text-align: right;">(<font color="green">0%</font>   -   0%)</td><td style="font-style:italic; text-align: right;">9359</td>
  </tr>
</table>

**Comment by rdelbru** [comment]
Deprecated
