### ISSUE TITLE
Correct the Boost of a TwigQuery

### ISSUE THREAD

**Issue by scampi** [rdelbru/SIREn#74]
> **FieldableNode**
> A query node implements FieldableNode interface to indicate that its children and itself are associated to a specific field.

The boost of a `FieldableNode` (e.g., a Term) is set using the `BoosQueryNodeProcessor`.
This processor visits each node of the tree and wraps it into a `BoostQueryNode`. The effect is that the englobed querynode is boosted with the associated boost value.

Because `TwigQueryNode` is a `FieldableNode`, this algorithm over-boost a `TwigQuery`.
For example, if we have configured 2 fields **a** and **b**, with the boost **1** and **2** respectively:

```
         TQ
      /      \
    Att      Val
    /          \
 Term1         AND
             /     \
          Term2    Term3
```

Using the `MultiFieldQueryNodeProcessor`, the tree is expanded over the two fields. We should have a `TwigQuery` boosted with 1, and another boosted with 2. However, the consequence of the `BoosQueryNodeProcessor` is that the terms `Term2` and `Term3` are also boosted.

This is wrong, the `TwigQuery` only should be boosted, not its children also.

**Comment by rdelbru** [comment]
Deprecated
