### ISSUE TITLE
SIREn doesnt build because of missing classes

### ISSUE THREAD

**Issue by ziqizhang** [rdelbru/SIREn#76]
Hi
I really want to use SIREn because we have a task to index triples using SOLR and SIREn sounds just the right solution.

I have downloaded 0.2.3, but the code doesnt compile.

currently im stuck with compiling the qparser module, where a lot of classes imports "org.sindice.siren.qparser.ntriple.query.model", which doesnt not exist in the code.

Please can someone help I am really desperate to get SIREn work!

Thanks!

**Comment by rdelbru** [comment]
Hi,

can you tried instead to download and compile the latest RC: https://github.com/rdelbru/SIREn/archive/0.2.3-RC2.tar.gz

**Comment by ziqizhang** [comment]
Hi 
Thanks for the very quick reply. I have solved the problem. It turned out to be the parser generators. Those missing classes have to be generated by the parser generators (jflex etc) first and I didnt know. I tried to set up the project in an IDE with the code and of course it failed.

When I followed exactly the maven build instruction as in "readme", it worked.

Thanks
