### ISSUE TITLE
Using URINormalisationFilter to tokenize a URL

### ISSUE THREAD

**Issue by ziqizhang** [rdelbru/SIREn#78]
Hi

I want to tokenize a URL into segements, e.g., 

http://www.w3.org/People/Berners-Lee/card.rdf
=>
http, www, w3, org, People, Berners, Lee, card, rdf

I have seen an example in URINormalisationFilter, which seems to be doing similar. However, when I have the following code, I ve seen that although it does tokenize the URL, many tokens (http, www, w3, org, Lee) are removed, which seems to be a stopwords behaviour and isnt what I want. I couldnt pinpoint where in the code it does this. Can experts give some explanation please?
## code:

public static void main(final String[] args) throws IOException {
    final TupleTokenizer stream = new TupleTokenizer(new StringReader("" +
            "_:node8634d6c3deee1fdec96ceae4 13a3e6eb http://renaud.delbru.fr/rdf/foaf " +
            "http://renaud.delbru.fr/  <http://xmlns.com/foaf/0.1/workplaceHomepage,_(Canada)/>"),
            Integer.MAX_VALUE);
    final TokenStream result = new URINormalisationFilter(stream);
    while (result.incrementToken()) {
      final CharTermAttribute termAtt = result.getAttribute(CharTermAttribute.class);
      final PositionIncrementAttribute posIncrAtt = result.getAttribute(PositionIncrementAttribute.class);
      System.out.println(termAtt.toString() + ", " + posIncrAtt.getPositionIncrement());

**Comment by rdelbru** [comment]
URINormalisationFilter removes automatically all generated tokens with less than 4 characters (see https://github.com/rdelbru/SIREn/blob/wip-0.2.3/siren-core/src/main/java/org/sindice/siren/analysis/filter/URINormalisationFilter.java#L125). You can remove this restriction, however we do not really advice to remove this, as it is likely that it will generate too many tokens, that will slow down your indexing process, increase your index size, etc.

**Comment by ziqizhang** [comment]
Thank you for the quick reply!
