### ISSUE TITLE
Indexing literals with language information

### ISSUE THREAD

**Issue by donkon** [rdelbru/SIREn#79]
When indexing N-Triple Literals with language information, e.g.

http://xmlns.com/foaf/0.1/name "Renaud Delbru"@de

the SirenPhraseQuery does not work as expected (i.e. does not find any Result).
Verifyd by running 
EntityCentricIndexing.getQuery1() and changing renaud.nt to the triple above.

**Comment by rdelbru** [comment]
Deprecated
