### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by sorinsarca** [rdelbru/SIREn#81]
Last commit was 2 years ago. I wonder if this project is still maintained or dead?

**Comment by atus** [comment]
I was wondering the same thing.. The last thing I found about them is this http://lists.deri.org/pipermail/siren/2012-October/000291.html where they talk about a new release but nothing has happened in a year.
I would love to just see this code updated and using lucene 4.x, updated caliper, etc.. Tried porting myself but it's way too complicated.

**Comment by ybilodray** [comment]
Hi, atus!

It has a continuation, with much more advanced features. Please write directly to Renaud.

**Comment by rdelbru** [comment]
Dear All,

SIREn 0.2 is not maintained anymore. We are focusing our effort on SIREn 1.0. Unfortunately, SIREn 1.0 is not yet open-source, but you can contact me at renaud at sindicetech dot com to get an evaluation license.

Kind Regards
